CREATE DATABASE svetadb;

CREATE USER 'muxamed'@'localhost' IDENTIFIED BY 'Qwerty1-';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON svetadb.* TO 'muxamed'@'localhost';